/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Perdoruesi;
import DAL.CourtException;
import DAL.PerdoruesiRepository;
import GUI.Model.AvokatiTableModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ArtonRamadani
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public MainForm(String roli) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        if (roli.equals("Administrator")) {
           
        } else if (roli.equals("Klient")) {
            menaxhoItem.setVisible(false);
            detyratMenuItem.setVisible(false);
            lendaMenuItem.setVisible(false);
        }else{
            shtoAvokatMenuItem.setVisible(false);
            shtoKlientinMenuItem.setVisible(false);
            shtoPunetorMenuItem.setVisible(false);
            perdoruesiMenuItem.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        courtMenu = new javax.swing.JMenu();
        avokatiMenuItem = new javax.swing.JMenuItem();
        detyratMenuItem = new javax.swing.JMenuItem();
        lendaMenuItem = new javax.swing.JMenuItem();
        menaxhoItem = new javax.swing.JMenu();
        shtoAvokatMenuItem = new javax.swing.JMenuItem();
        shtoKlientinMenuItem = new javax.swing.JMenuItem();
        shtoPunetorMenuItem = new javax.swing.JMenuItem();
        depMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        perdoruesiMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("LogOut");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        courtMenu.setText("Court");

        avokatiMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_home_32px.png"))); // NOI18N
        avokatiMenuItem.setText("Dashboard");
        avokatiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avokatiMenuItemActionPerformed(evt);
            }
        });
        courtMenu.add(avokatiMenuItem);

        detyratMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_todo_list_32px.png"))); // NOI18N
        detyratMenuItem.setText("Detyrat");
        detyratMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detyratMenuItemActionPerformed(evt);
            }
        });
        courtMenu.add(detyratMenuItem);

        lendaMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_briefcase_32px.png"))); // NOI18N
        lendaMenuItem.setText("Lenda");
        lendaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendaMenuItemActionPerformed(evt);
            }
        });
        courtMenu.add(lendaMenuItem);

        menuBar.add(courtMenu);

        menaxhoItem.setText("Menaxho");

        shtoAvokatMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_collaborator_32px.png"))); // NOI18N
        shtoAvokatMenuItem.setText("Shto Avokat");
        shtoAvokatMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shtoAvokatMenuItemActionPerformed(evt);
            }
        });
        menaxhoItem.add(shtoAvokatMenuItem);

        shtoKlientinMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_user_male_30px.png"))); // NOI18N
        shtoKlientinMenuItem.setText("Shto Klientin");
        shtoKlientinMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shtoKlientinMenuItemActionPerformed(evt);
            }
        });
        menaxhoItem.add(shtoKlientinMenuItem);

        shtoPunetorMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_32px.png"))); // NOI18N
        shtoPunetorMenuItem.setText("Shto Punetor");
        shtoPunetorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shtoPunetorMenuItemActionPerformed(evt);
            }
        });
        menaxhoItem.add(shtoPunetorMenuItem);

        depMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_department_32px.png"))); // NOI18N
        depMenuItem.setText("Departamenti");
        depMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depMenuItemActionPerformed(evt);
            }
        });
        menaxhoItem.add(depMenuItem);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checked_truck_32px.png"))); // NOI18N
        jMenuItem1.setText("Furnitori");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menaxhoItem.add(jMenuItem1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_high_priority_24px_1.png"))); // NOI18N
        jMenuItem4.setText("Prioriteti");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menaxhoItem.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_payment_history_24px.png"))); // NOI18N
        jMenuItem5.setText("LlojiPageses");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menaxhoItem.add(jMenuItem5);

        perdoruesiMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_32px.png"))); // NOI18N
        perdoruesiMenuItem.setText("Perdoruesi");
        perdoruesiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perdoruesiMenuItemActionPerformed(evt);
            }
        });
        menaxhoItem.add(perdoruesiMenuItem);

        menuBar.add(menaxhoItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
      
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void avokatiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avokatiMenuItemActionPerformed
       
    }//GEN-LAST:event_avokatiMenuItemActionPerformed

    private void lendaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendaMenuItemActionPerformed
        LendaForm lf = new LendaForm();
        desktopPane.add(lf);
        lf.show();
    }//GEN-LAST:event_lendaMenuItemActionPerformed

    private void detyratMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detyratMenuItemActionPerformed
        DetyraForm df = new DetyraForm();
        desktopPane.add(df);
        df.show();
    }//GEN-LAST:event_detyratMenuItemActionPerformed

    private void depMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depMenuItemActionPerformed
        DepartamentiForm df = new DepartamentiForm();
        desktopPane.add(df);
        df.show();
    }//GEN-LAST:event_depMenuItemActionPerformed

    private void perdoruesiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perdoruesiMenuItemActionPerformed
        PerdoruesiForm pff = new PerdoruesiForm();
        desktopPane.add(pff);
        pff.show();
    }//GEN-LAST:event_perdoruesiMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FurnitoriForm ff = new FurnitoriForm();
        desktopPane.add(ff);
        ff.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void shtoAvokatMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shtoAvokatMenuItemActionPerformed
        AvokatiForm af = new AvokatiForm();
        desktopPane.add(af);
        af.show();
    }//GEN-LAST:event_shtoAvokatMenuItemActionPerformed

    private void shtoKlientinMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shtoKlientinMenuItemActionPerformed
        KlientiForm kf = new KlientiForm();
        desktopPane.add(kf);
        kf.show();
    }//GEN-LAST:event_shtoKlientinMenuItemActionPerformed

    private void shtoPunetorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shtoPunetorMenuItemActionPerformed
        PunonjesForm pff = new PunonjesForm();
        desktopPane.add(pff);
        pff.show();
    }//GEN-LAST:event_shtoPunetorMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        PrioritetiForm pf = new PrioritetiForm();
        desktopPane.add(pf);
        pf.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        LlojiPagesesForm lp = new LlojiPagesesForm();
        desktopPane.add(lp);
        lp.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem avokatiMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenu courtMenu;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem depMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem detyratMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem lendaMenuItem;
    private javax.swing.JMenu menaxhoItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem perdoruesiMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem shtoAvokatMenuItem;
    private javax.swing.JMenuItem shtoKlientinMenuItem;
    private javax.swing.JMenuItem shtoPunetorMenuItem;
    // End of variables declaration//GEN-END:variables

}
